### ISSUE TITLE
i still unknown how to use your tools

### ISSUE THREAD

**Issue by luoying1105** [veer66/thailang4r#2]
i have install 
but how to use it

**Comment by tchayintr** [comment]
@luoying1105 
Have you try the code below in ruby console?
```ruby
# encoding: UTF-8`
require 'thailang4r/word_breaker'
word_breaker = ThaiLang::WordBreaker.new
puts word_breaker.break_into_words("ฉันกินข้าว")
```

This link will describes you about how to run a ruby code or file on your terminal
https://stackoverflow.com/questions/12378818/how-to-run-ruby-code-from-terminal
